/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SudokuLib */

#ifndef _Included_SudokuLib
#define _Included_SudokuLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SudokuLib
 * Method:    CreateBoolMatrix
 * Signature: (III)J
 */
JNIEXPORT jlong JNICALL Java_SudokuLib_CreateBoolMatrix
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     SudokuLib
 * Method:    DestroyBoolMatrix
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_SudokuLib_DestroyBoolMatrix
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SudokuLib
 * Method:    SetMatrixRowData
 * Signature: (J[I)V
 */
JNIEXPORT void JNICALL Java_SudokuLib_SetMatrixRowData
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     SudokuLib
 * Method:    DancingLinks
 * Signature: (JILMatrixCallback;)I
 */
JNIEXPORT jint JNICALL Java_SudokuLib_DancingLinks
  (JNIEnv *, jclass, jlong, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
