/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SudokuLib */

#ifndef _Included_SudokuLib
#define _Included_SudokuLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SudokuLib
 * Method:    CreateBoolMatrix
 * Signature: (III)J
 */
JNIEXPORT jlong JNICALL Java_SudokuLib_CreateBoolMatrix
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     SudokuLib
 * Method:    DestroyBoolMatrix
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_SudokuLib_DestroyBoolMatrix
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SudokuLib
 * Method:    SetMatrixRowData
 * Signature: (J[I)V
 */
JNIEXPORT void JNICALL Java_SudokuLib_SetMatrixRowData
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     SudokuLib
 * Method:    DancingLinks
 * Signature: (JILIMatrixCallback;)I
 */
JNIEXPORT jint JNICALL Java_SudokuLib_DancingLinks
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     SudokuLib
 * Method:    CreateSudoku
 * Signature: (LISudokuCallback;)J
 */
JNIEXPORT jlong JNICALL Java_SudokuLib_CreateSudoku
  (JNIEnv *, jclass, jobject);

/*
 * Class:     SudokuLib
 * Method:    DestroySudoku
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_SudokuLib_DestroySudoku
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SudokuLib
 * Method:    VerifySudokuBoard
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_SudokuLib_VerifySudokuBoard
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     SudokuLib
 * Method:    VerifySudoku
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SudokuLib_VerifySudoku
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SudokuLib
 * Method:    GetKnownCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SudokuLib_GetKnownCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SudokuLib
 * Method:    MakeResultString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SudokuLib_MakeResultString
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SudokuLib
 * Method:    CalculateSudokuAll
 * Signature: (JILISudokuAnswerCallback;)I
 */
JNIEXPORT jint JNICALL Java_SudokuLib_CalculateSudokuAll
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     SudokuLib
 * Method:    SolveTypeName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SudokuLib_SolveTypeName
  (JNIEnv *, jclass, jint);

/*
 * Class:     SudokuLib
 * Method:    ImproveTypeName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SudokuLib_ImproveTypeName
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
